version: '3.8'
services:
  server:
    build: .
    image: app
    container_name: app_container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/dockerDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    networks:
      - app_network

  db:
    hostname: db
    image: postgres:13.7-alpine
    container_name: db_container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=dockerDB
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
